# Generated by Django 4.1.1 on 2022-09-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
