# Generated by Django 4.1.1 on 2022-09-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='character',
            name='lastName',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
