# Generated by Django 4.1.1 on 2022-09-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_rename_name_character_firstname_character_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lastName',
        ),
    ]
