# Generated by Django 4.1.1 on 2022-09-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_rename_firstname_character_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.AddField(
            model_name='character',
            name='baseStats',
            field=models.CharField(default=(1, 2, 3, 4, 5, 6), max_length=200),
            preserve_default=False,
        ),
    ]
