# Generated by Django 4.1.1 on 2022-10-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0009_remove_character_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='charClass',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='playerName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
