# Generated by Django 4.1.1 on 2022-10-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0010_character_alignment_character_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
