# Generated by Django 4.1.1 on 2022-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_character_armor_character_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='skillRanks',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
