# Generated by Django 4.1.1 on 2022-10-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0012_character_gold_character_skillranks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='traits',
            field=models.JSONField(),
        ),
    ]
