# Generated by Django 4.1.1 on 2022-10-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0013_alter_character_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='edition',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
