# Generated by Django 4.1.1 on 2022-10-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0014_character_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
