# Generated by Django 4.1.1 on 2022-10-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0015_character_feats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='feats',
            field=models.JSONField(),
        ),
    ]
