# Generated by Django 4.1.1 on 2022-10-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0016_alter_character_feats'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='config',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
