# Generated by Django 4.1.1 on 2022-10-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0017_character_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='edition',
        ),
    ]
